"""
Create Approval Request Skill

Specification: AGENT-SKILLS-002

Purpose: Generate approval request files for actions requiring human oversight

Input:
    - action_type: str (email_send, payment, file_operation, etc.)
    - action_details: dict with action-specific details
    - vault_path: str path to vault root
    
Output:
    - Creates file in /Pending_Approval/
    - Returns path to created file
"""

import sys
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any, Optional


def create_approval_request(
    vault_path: str,
    action_type: str,
    action_details: Dict[str, Any],
    priority: str = "medium",
    expires_hours: int = 24
) -> Dict[str, Any]:
    """
    Create an approval request file.
    
    Args:
        vault_path: Path to Obsidian vault root
        action_type: Type of action requiring approval
        action_details: Dictionary with action-specific details
        priority: low, medium, high, urgent
        expires_hours: Hours until approval expires
        
    Returns:
        Dict: Result with success status and file path
    """
    result = {
        'success': False,
        'file_path': None,
        'error': None
    }
    
    try:
        vault = Path(vault_path)
        approval_dir = vault / 'Pending_Approval'
        approval_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate unique filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        action_id = action_details.get('id', f"{action_type}_{timestamp}")
        safe_id = ''.join(c if c.isalnum() or c in '-_' else '_' for c in str(action_id))
        filename = f"APPROVAL_{safe_id}_{timestamp}.md"
        filepath = approval_dir / filename
        
        # Calculate expiration
        expires = datetime.now() + timedelta(hours=expires_hours)
        
        # Build details section based on action type
        details_section = build_details_section(action_type, action_details)
        instructions = build_instructions(action_type, action_details)
        
        # Build frontmatter
        frontmatter = {
            'type': 'approval_request',
            'action': action_type,
            'created': datetime.now().isoformat(),
            'expires': expires.isoformat(),
            'priority': priority,
            'status': 'pending'
        }
        
        # Add action-specific frontmatter
        for key, value in action_details.items():
            if key not in ['description', 'content']:
                frontmatter[f'detail_{key}'] = value
        
        # Build frontmatter string
        frontmatter_str = "---\n"
        for key, value in frontmatter.items():
            frontmatter_str += f"{key}: {value}\n"
        frontmatter_str += "---\n\n"
        
        # Build content
        priority_emoji = {'low': '🟢', 'medium': '🟡', 'high': '🟠', 'urgent': '🔴'}.get(priority, '🟡')
        
        content = f"""{frontmatter_str}# {priority_emoji} Approval Required: {action_type.replace('_', ' ').title()}

{details_section}
## Instructions

{instructions}

**To Approve:**
1. Review the details above
2. Move this file to `/Approved/` folder
3. AI Employee will proceed with the action

**To Reject:**
1. Move this file to `/Rejected/` folder
2. Optionally add a note explaining why

**To Modify:**
1. Edit this file with your changes
2. Move to `/Approved/` when ready

---

## Metadata

- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Expires:** {expires.strftime('%Y-%m-%d %H:%M')} ({expires_hours} hours)
- **Priority:** {priority.title()}

---
*Generated by AI Employee v1.0.0*
"""
        
        # Write file
        filepath.write_text(content, encoding='utf-8')
        
        result['success'] = True
        result['file_path'] = str(filepath)
        
    except Exception as e:
        result['error'] = str(e)
    
    return result


def build_details_section(action_type: str, details: Dict[str, Any]) -> str:
    """
    Build the details section based on action type.
    
    Args:
        action_type: Type of action
        details: Action details
        
    Returns:
        str: Formatted details section
    """
    if action_type == 'email_send':
        return f"""## Email Details

| Field | Value |
|-------|-------|
| **To** | {details.get('to', 'Not specified')} |
| **Subject** | {details.get('subject', 'Not specified')} |
| **Priority** | {details.get('priority', 'normal')} |

## Email Content

{details.get('body', details.get('content', 'No content provided'))}

{f"## Attachment: {details.get('attachment', 'None')}" if details.get('attachment') else ""}
"""
    
    elif action_type == 'payment':
        return f"""## Payment Details

| Field | Value |
|-------|-------|
| **Amount** | ${details.get('amount', '0.00')} |
| **Recipient** | {details.get('recipient', 'Not specified')} |
| **Reference** | {details.get('reference', 'Not specified')} |
| **Due Date** | {details.get('due_date', 'Not specified')} |

## Payment Information

{details.get('description', details.get('notes', 'No additional information'))}

⚠️ **Note:** This payment requires human approval as per Company Handbook rules.
"""
    
    elif action_type == 'social_post':
        return f"""## Social Media Post Details

| Field | Value |
|-------|-------|
| **Platform** | {details.get('platform', 'Not specified')} |
| **Content** | {details.get('content', 'No content provided')} |
| **Scheduled Time** | {details.get('scheduled_time', 'Immediate')} |

{f"## Image/Media: {details.get('media', 'None')}" if details.get('media') else ""}
"""
    
    elif action_type == 'file_operation':
        return f"""## File Operation Details

| Field | Value |
|-------|-------|
| **Operation** | {details.get('operation', 'Not specified')} |
| **Source** | {details.get('source', 'Not specified')} |
| **Destination** | {details.get('destination', 'Not specified')} |

## Description

{details.get('description', details.get('notes', 'No additional information'))}
"""
    
    elif action_type == 'meeting_schedule':
        return f"""## Meeting Details

| Field | Value |
|-------|-------|
| **Title** | {details.get('title', 'Not specified')} |
| **Attendees** | {', '.join(details.get('attendees', []))} |
| **Proposed Time** | {details.get('proposed_time', 'Not specified')} |
| **Duration** | {details.get('duration', 'Not specified')} |

## Description

{details.get('description', details.get('notes', 'No additional information'))}
"""
    
    else:
        # Generic details
        details_list = '\n'.join([f"- **{k.replace('_', ' ').title()}:** {v}" for k, v in details.items()])
        return f"""## Details

{details_list}
"""


def build_instructions(action_type: str, details: Dict[str, Any]) -> str:
    """
    Build instructions based on action type.
    
    Args:
        action_type: Type of action
        details: Action details
        
    Returns:
        str: Formatted instructions
    """
    instructions = {
        'email_send': """This email is ready to send. Please review:
- Recipient email address is correct
- Content is appropriate and professional
- Any attachments are included""",
        
        'payment': """This payment requires your authorization. Please verify:
- Amount is correct
- Recipient is legitimate
- Payment is due and authorized
- Reference/invoice number is correct""",
        
        'social_post': """This social media post is ready to publish. Please review:
- Content aligns with brand voice
- No typos or errors
- Timing is appropriate
- Any media attachments are correct""",
        
        'file_operation': """This file operation will be performed. Please confirm:
- Source file/folder exists
- Destination is correct
- Operation won't cause data loss
- You understand the consequences""",
        
        'meeting_schedule': """This meeting is ready to schedule. Please confirm:
- Time works with your schedule
- Attendees are appropriate
- Duration is sufficient
- Meeting purpose is clear"""
    }
    
    return instructions.get(action_type, """Please review this action carefully. Consider:
- Is this action appropriate?
- Are all details correct?
- Are there any risks or concerns?
- Should any modifications be made?""")


def main():
    """
    Main entry point for testing the skill.
    
    Usage:
        python create_approval_request.py <vault_path> <action_type> [details_json]
    """
    import json
    
    if len(sys.argv) < 3:
        print("Usage: python create_approval_request.py <vault_path> <action_type> [details_json]")
        sys.exit(1)
    
    vault_path = sys.argv[1]
    action_type = sys.argv[2]
    
    # Parse details if provided
    details = {}
    if len(sys.argv) > 3:
        try:
            details = json.loads(sys.argv[3])
        except json.JSONDecodeError:
            print("Error: Invalid JSON for details")
            sys.exit(1)
    
    result = create_approval_request(
        vault_path=vault_path,
        action_type=action_type,
        action_details=details
    )
    
    print(json.dumps(result, indent=2, default=str))


if __name__ == '__main__':
    main()
